=== AryanBiswari/music-player-xml/playlist.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="music">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="track" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string" />
                            <xs:element name="artist" type="xs:string" />
                            <xs:element name="album" type="xs:string" />
                            <xs:element name="duration" type="xs:string" />
                            <xs:element name="images" type="xs:string" />
                            <xs:element name="file" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== AryanBiswari/music-player-xml/playlist.xml
<?xml version="1.0" encoding="UTF-8"?>
<music xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="playlist.xsd">
  <track>
    <name>Allah Duhai</name>
    <artist>Amit Mishra</artist>
    <album>RACE 3</album>
    <duration>04:39</duration>
    <images>images/race3.jpg</images>
    <file>audios/Allah-Duhai-Hai(PagalWorld).mp3</file>
  </track>
  <track>
    <name>Gallan Goodiyan</name>
    <artist>Farhan Akhtar</artist>
    <album>DIL DHADAKNE DO</album>
    <duration>04:56</duration>
    <images>images/dil.jpg</images>
    <file>audios/Gallan Goodiyaan.mp3</file>
  </track>
</music>
